### ISSUE TITLE
v1 and v2 generates different output

### ISSUE THREAD

**Issue by wobba** [wobba/AzureFunction-SwaggerDefinition#9]
The output swagger is not identical for v1/v2.

**Comment by joeljeffery** [comment]
Odd! It seems to fail on Result<bool> (i.e. Template1)... but not Result<string> (Template2)

![image](https://user-images.githubusercontent.com/20968935/46598278-80104a80-cadb-11e8-994b-d3c6ee10ab6b.png)

I'll see if I can find out why.

**Comment by joeljeffery** [comment]
Fixed! See https://github.com/wobba/AzureFunction-SwaggerDefinition/pull/10.
